"use strict";
// auto-generated by `jswt reexport`
// DO NOT EDIT

module.exports = require("./lib/jswt.js")

// these typedef reexports will be available to dependent packages
/**
 * @typedef {import('./bin/jswt-init.js').MyError} MyError
 * @typedef {import('./bin/jswt-reexport.js').Typedef} Typedef
 */
